core/models.py
from core import db, login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)

    def __repr__(self):
        return f"User({self.id}, {self.username}, {self.email})"

core/user/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    PasswordField,
    SubmitField,
    EmailField,
)
from wtforms.validators import (
    DataRequired,
    Length,
    ValidationError,
)
from core.models import User


class RegistrationForm(FlaskForm):
    username = StringField(
        "Username", validators=[DataRequired(), Length(min=4, max=20)]
    )
    email = EmailField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Done")

    @staticmethod
    def validate_username(username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                "That username is taken. Please choose a different one"
            )

    @staticmethod
    def validate_email(email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError(
                "That email is taken. Please choose a different one"
            )


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")

core/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

from core.settings import create_path_to_db, Config


db = SQLAlchemy()

login_manager = LoginManager()


def register_extensions(app):

    db.init_app(app)

    login_manager.init_app(app)


def register_blueprints(app):
    from core.routes import main
    from core.user.routes import users

    app.register_blueprint(main)
    app.register_blueprint(users)


def configure_database(app):
    create_path_to_db()

    @app.before_first_request
    def initialize_database():
        db.create_all()

    @app.teardown_request
    def shutdown_session(exception=None):
        db.session.remove()


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    register_extensions(app)
    configure_database(app)
    register_blueprints(app)

    return app

core/routes.py
import requests
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    jsonify,
)
from flask_login import login_required, current_user


from scrapper import scraping, BeautifulSoup

main = Blueprint("main", __name__, template_folder="core/templates")


@main.route("/index", methods=["GET", "POST"])
@login_required
def index():

    return render_template("index.html")


@main.route("/scraping", methods=["GET", "POST"])
def scrap():
    if request.method == "GET":
        return redirect(url_for("main.index"))

    phones = scraping()

    return jsonify(
        {"htmlresponse": render_template("response.html", phones=phones)}
    )


@main.route("/image", methods=["POST"])
def get_image():
    if request.method == "GET":
        return redirect(url_for("main.index"))

    phone = request.form["link"]

    response = requests.get(phone)

    soup = BeautifulSoup(response.content, "html.parser")
    try:
        image = soup.select_one(".css-1bmvjcs")["src"].split(";")[0]
    except TypeError:
        image = "Image not Found"
    return jsonify({"image": image, "link": phone})


@main.route("/")
def home():
    if current_user.is_anonymous:
        return redirect(url_for("users.login"))
    return redirect(url_for("main.index"))

core/user/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from wtforms import ValidationError

from core import db
from core.models import User
from core.user.forms import LoginForm, RegistrationForm

users = Blueprint("users", __name__, template_folder="templates")


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = RegistrationForm()
    if request.method == "POST":
        if form.validate_on_submit:
            hashed_password = generate_password_hash(form.password.data)

            user = User(
                username=form.username.data,
                email=form.email.data,
                password=hashed_password,
            )
            try:
                form.validate_email(form.email)
                form.validate_username(form.username)
                db.session.add(user)
                db.session.commit()
                return redirect(url_for("users.login"))
            except ValidationError as e:
                flash(str(e))

    return render_template("user/register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = LoginForm()
    if request.method == "POST":
        if form.validate_on_submit:
            user = User.query.filter_by(email=form.email.data).first()
            if user:
                cph = check_password_hash(user.password, form.password.data)
                if cph:
                    login_user(user)
                    return redirect(url_for("main.index"))
                else:
                    flash("Wrong password!")
            else:
                flash("User not found!")

    return render_template("user/login.html", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))

core/templates/index.html
{% extends "layout.html"%}
{% block content %}
<div class="text-center">
  <h4>Привет, {{ current_user.username }}.
    <a href="/logout" class="btn btn-danger">
    Выйти <i class="fas fa-sign-out-alt"></i>
    </a>
  </h4>
  <h1>Количество обьявлений: <span class="badge badge-primary" id="counter"></span></h1>
  <button type="button" class="update-info btn btn-primary">Обновить</button>
</div>
<div class="advert">
  {% include "response.html" %}
</div>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<script>
  $(document).ready(function(){
      $('.update-info').click(function(){

          $.ajax({
              url: '{{ url_for("main.scrap") }}',

              type: 'post',
              success: function(data){
                  $(`.advert`).html(data.htmlresponse);
                  $('#counter').text($('.card-body').length);

              }
          });
      });
  });

</script>
{% endblock %}

core/templates/layout.html
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
      />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
      />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css"
      rel="stylesheet"
      />
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"
      ></script>
  </head>
  <body>
    {% block content %}
    {% endblock  %}
  </body>
</html>

core/templates/response.html
<div class="row row-cols-1 row-cols-md-3 g-4 phones">
  {% for phone in phones %}
  <div class="col" id="{{ phone["id"] }}">
  <div class="card h-100">
    <div class="card-body">
      <h5 class="card-title">{{ phone["phone"] }}</h5>
      <p class="card-text">
        {{ phone["price"] }}
      </p>
      <button class="imagelink btn btn-primary" data-id="{{ phone["link"] }}" data-title="{{ phone["phone"] }}">View photo</button>
      <button class="btn btn-danger" onclick="
      $('#{{ phone["id"] }}').remove();
      $('#counter').text($('.card-body').length);
      ">Delete</button>
    </div>
    <div class="card-footer">
      <small class="text-muted">{{ phone["date"] }}</small>
    </div>
  </div>
</div>
{% endfor %}
</div>
<script type='text/javascript'>
  $(document).ready(function(){
      $('.imagelink').click(function(){
          let link = $(this).data('id');
          let title = $(this).data('title');
          let image = document.getElementById("phone_image");
          let olx = document.getElementById("olx");

          $.ajax({
              url: '{{ url_for("main.get_image") }}',
              type: 'post',
              data: {link: link},
              success: function(data){
                  $(`.modal-title`).text(title);
                  image.src = data.image;
                  olx.href = link;
                  $(`#exampleModal`).modal('show');
              }
          });
      });
  });
</script>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <img src="" alt="" id="phone_image" style="
          width: 100%;
          "/>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
        <a href="" class="btn btn-primary" id="olx">Go to OLX</a>
      </div>
    </div>
  </div>
</div>

core/templates/user/login.html
{% extends 'layout.html'%}
{% block content%}
<form action="" method="post">
  <section class="vh-100" style="background-color: #508bfc;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card shadow-2-strong" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
              <h3 class="mb-5">Sign in</h3>
              <div class="form-outline mb-4">
                <input type="email" required id="email" name="email" class="form-control form-control-lg" />
                <label class="form-label" for="email">{{ form.email.label}}</label>
              </div>
              <div class="form-outline mb-4">
                <input type="password" id="password" name="password" class="form-control form-control-lg" />
                <label class="form-label" for="password">{{ form.password.label }}</label>
              </div>
              <button id="submit" name="submit" class="btn btn-primary btn-lg btn-block" type="submit">
              {{ form.submit.label }}</button>
              <hr class="my-4">
              <div class="text-center">
                <p>Not a member? <a href="/register">Register</a></p>
              </div>
              {% with messages = get_flashed_messages() %}
              {% if messages %}
              {% for message in messages %}
              <div class="note note-danger mb-3">
                <strong>Error:</strong> {{ message }}
              </div>
              {% endfor %}
              {% endif %}
              {% endwith %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</form>
{% endblock %}

core/templates/user/register.html
{% extends 'layout.html'%}
{% block content%}
<form action="" method="post">
  <section class="vh-100" style="background-color: #508bfc;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card shadow-2-strong" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">
              <h3 class="mb-5">Registration</h3>
              <div class="form-outline mb-4">
                <input type="email" required id="email" name="email" class="form-control form-control-lg" />
                <label class="form-label" for="email">{{ form.email.label}}</label>
              </div>
              <div class="form-outline mb-4">
                <input type="text" required id="username" name="username" class="form-control form-control-lg" />
                <label class="form-label" for="username">{{ form.username.label}}</label>
              </div>
              <div class="form-outline mb-4">
                <input type="password" id="password" name="password" class="form-control form-control-lg" />
                <label class="form-label" for="password">{{ form.password.label }}</label>
              </div>
              <button id="submit" name="submit" class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
              {% with messages = get_flashed_messages() %}
              {% if messages %}
              {% for message in messages %}
              <div class="note note-danger mb-3">
                <strong>Error:</strong> {{ message }}
              </div>
              {% endfor %}
              {% endif %}
              {% endwith %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</form>
{% endblock %}